#!/usr/bin/env python3

# Generates AllGuis.h into the build folder, its path is passed in as the first argument
#
# plugdata needs to read fields from objects whose struct definitions live inside a .c file
# of pd, ELSE or cyclone, and are therefore not visible to us. We used to keep hand-written
# copies of those structs, which silently went out of sync whenever one of the libraries was
# updated. This copies them straight out of the library sources instead, so re-running cmake
# is all it takes after updating a submodule.
#
# The struct body is copied verbatim, so any preprocessor conditionals in it are resolved by
# whoever includes AllGuis.h. Types that are private to the source file are substituted using
# the REPLACE table below; if you add a struct that references a new one, add it there too.

import datetime
import os
import re
import sys

PD = "pure-data/src/"
PD_EXTRA = "pure-data/extra/"
ELSE = "pd-else/Source/"
CYCLONE = "pd-cyclone/cyclone_objects/binaries/"

# (generated name, source file relative to Libraries/, struct tag, comment)
STRUCTS = [
    ("t_fake_gatom", PD + "g_text.c", "_gatom", "[floatatom], [symbolatom], [listbox]"),
    ("t_fake_garray", PD + "g_array.c", "_garray", "[array]"),
    ("t_fake_button", ELSE + "Control/button.c", "_button", "[else/button]"),
    ("t_fake_clone", PD + "g_clone.c", "_clone", "[clone]"),
    ("t_fake_colors", ELSE + "Control/colors.c", "_colors", "[else/colors]"),
    ("t_fake_function", ELSE + "Control/function.c", "_function", "[else/function]"),
    ("t_fake_keyboard", ELSE + "Control/keyboard.c", "_keyboard", "[else/keyboard]"),
    ("t_fake_knob", ELSE + "Control/knob.c", "_knob", "[else/knob]"),
    ("t_fake_messbox", ELSE + "Control/messbox.c", "_messbox", "[else/messbox]"),
    ("t_fake_pad", ELSE + "Control/pad.c", "_pad", "[else/pad]"),
    ("t_fake_note", ELSE + "Control/note.c", "_note", "[else/note]"),
    ("t_fake_numbox", ELSE + "Audio/numbox~.c", "_numbox", "[else/numbox~]"),
    ("t_fake_canvas_mouse", ELSE + "Control/canvas.mouse.c", "_canvas_mouse", "[else/canvas.mouse]"),
    ("t_fake_zoom", ELSE + "Control/canvas.zoom.c", "_zoom", "[else/canvas.zoom]"),
    ("t_fake_edit", ELSE + "Control/canvas.edit.c", "_edit", "[else/canvas.edit]"),
    ("t_fake_canvas_vis", ELSE + "Control/canvas.vis.c", "_canvas_vis", "[else/canvas.vis]"),
    ("t_fake_mouse", ELSE + "Control/mouse.c", "_mouse", "[else/mouse]"),
    ("t_fake_pic", ELSE + "Control/pic.c", "_pic", "[else/pic]"),
    ("t_fake_fielddesc", PD + "g_template.c", "_fielddesc", "for template drawing"),
    ("t_fake_curve", PD + "g_template.c", "_curve", "for template drawing"),
    ("t_fake_drawnumber", PD + "g_template.c", "_drawtext", "[drawnumber], [drawsymbol], [drawtext]"),
    ("t_fake_plot", PD + "g_template.c", "_plot", "[plot]"),
    ("t_fake_scope", ELSE + "Audio/scope~.c", "_scope", "[else/scope~]"),
    ("t_fake_textbuf", PD + "x_text.c", "_textbuf", "shared by [text define] and [qlist]"),
    ("t_fake_qlist", PD + "x_text.c", "_qlist", "[qlist]"),
    ("t_fake_text_define", PD + "x_text.c", "_text_define", "[text define]"),
    ("t_fake_pd_tilde", PD_EXTRA + "pd~/pd~.c", "_pd_tilde", "[pd~]"),
    ("t_fake_mousestate", CYCLONE + "control/mousestate.c", "_mousestate", "[cyclone/MouseState]"),
    ("t_fake_keycode", ELSE + "Control/keycode.c", "_keycode", "[else/keycode]"),
    ("t_fake_menu", ELSE + "Control/popmenu.c", "_menu", "[else/popmenu]"),
]

# Global whole-word find/replace, applied to the finished header. Use it for definitions we
# don't have: types that are private to the file we copy from map to void, since we only ever
# hold a pointer to them, and types we generate ourselves map to their t_fake_ name
REPLACE = {
    "t_fielddesc": "t_fake_fielddesc",
    "t_textbuf": "t_fake_textbuf",
    "t_canvas_mouse_proxy": "void",
    "t_canvas_vis_proxy": "void",
    "t_edit_proxy": "void",
    "t_messbox_proxy": "void",
    "t_zoom_proxy": "void",
    "t_copy": "void",
    "t_in": "void",
    "t_out": "void",
    "t_pdsample": "t_sample",
}

# Written above the structs. The array sizes here are the one thing not copied from the
# sources, so they have to be kept in sync by hand
PREAMBLE = """/*
 // Copyright (c) {year} Timothy Schoen
 // For information on usage and redistribution, and for a DISCLAIMER OF ALL
 // WARRANTIES, see the file, "LICENSE.txt," in this distribution.
 */

// This file is generated by Resources/Scripts/generate_all_guis.py, do not edit it by hand.
// It holds copies of struct definitions that are private to the pd, ELSE and cyclone sources,
// so that plugdata can read their fields. Re-run cmake after updating one of those libraries,
// and add new structs to the STRUCTS list in the script.

#pragma once
#include <g_canvas.h>

#define MAX_NUMBOX_LEN 32    // else/knob, else/numbox~
#define SCOPE_MAXBUFSIZE 256 // else/scope~

// clang-format off
"""


def extract_struct(text, tag, source):
    # Finds "struct <tag> {" and returns the braces and everything between them
    match = re.search(r"\bstruct\s+" + re.escape(tag) + r"\s*\{", text)
    if not match:
        raise LookupError("could not find 'struct %s' in %s" % (tag, source))

    start = text.index("{", match.start())
    depth = 0
    for index in range(start, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[start:index + 1]
    raise LookupError("unterminated 'struct %s' in %s" % (tag, source))


def generate(root):
    output = [PREAMBLE.format(year=datetime.date.today().year)]

    for name, source, tag, comment in STRUCTS:
        path = os.path.join(root, "Libraries", source)
        if not os.path.exists(path):
            raise LookupError("missing %s, did you check out the submodules?" % source)
        with open(path, "r", encoding="utf-8", errors="replace") as file:
            body = extract_struct(file.read(), tag, source)

        output.append("// %s (%s)\nstruct %s %s;\n" % (comment, source, name, body))

    output.append("// clang-format on\n")

    # \w+ only ever matches a whole identifier, so this can't rewrite part of a longer name
    return re.sub(r"\w+", lambda m: REPLACE.get(m.group(0), m.group(0)), "\n".join(output))


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: generate_all_guis.py <output path for AllGuis.h>\n")
        return 1

    root = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
    destination = os.path.abspath(sys.argv[1])

    try:
        content = generate(root)
    except LookupError as error:
        sys.stderr.write("generate_all_guis.py: %s\n" % error)
        return 1

    os.makedirs(os.path.dirname(destination), exist_ok=True)

    if os.path.exists(destination):
        with open(destination, "r", encoding="utf-8") as file:
            if file.read() == content:
                return 0

    with open(destination, "w", encoding="utf-8", newline="\n") as file:
        file.write(content)
    print("Regenerated %s" % destination)
    return 0


if __name__ == "__main__":
    sys.exit(main())
