highshelf~.class.sources := highshelf~.c 
lowshelf~.class.sources := lowshelf~.c 
bandpass~.class.sources := bandpass~.c 
bandstop~.class.sources := bandstop~.c 
lowpass~.class.sources := lowpass~.c 
highpass~.class.sources := highpass~.c 
resonant~.class.sources := resonant~.c 
allpass.2nd~.class.sources := allpass.2nd~.c 
eq~.class.sources := eq~.c 







# include Makefile.pdlibbuilder from submodule directory 'pd-lib-builder'
PDLIBBUILDER_DIR=pd-lib-builder/
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder
