/*
 // Copyright (c) 2021-2025 Timothy Schoen
 // For information on usage and redistribution, and for a DISCLAIMER OF ALL
 // WARRANTIES, see the file, "LICENSE.txt," in this distribution.
 */

// Generated by Resources/Fonts/IconFont/build_icon_font.py from
// Resources/Fonts/IconFont/icons.json, alongside Resources/Fonts/IconFont.ttf.
// Do not edit: add the icon to icons.json and rebuild, or the name and the glyph
// it selects will disagree.

#pragma once

#include "Utility/Config.h"

struct Icons {
    // GUI ICONS
    static inline String const Open = CharPointer_UTF8("\xee\x80\x80");
    static inline String const Folder = CharPointer_UTF8("\xee\x80\x80");
    static inline String const Save = CharPointer_UTF8("\xee\x80\x81");
    static inline String const SaveAs = CharPointer_UTF8("\xee\x80\x82");
    static inline String const Undo = CharPointer_UTF8("\xee\x80\x83");
    static inline String const Redo = CharPointer_UTF8("\xee\x80\x84");
    static inline String const Add = CharPointer_UTF8("\xee\x80\x85");
    static inline String const AddObject = CharPointer_UTF8("\xee\x80\x86");
    static inline String const Settings = CharPointer_UTF8("\xee\x80\x87");
    static inline String const Sparkle = CharPointer_UTF8("\xee\x80\x88");
    static inline String const SparkleFilled = CharPointer_UTF8("\xee\x80\x89");
    static inline String const CPU = CharPointer_UTF8("\xee\x80\x8a");
    static inline String const Clear = CharPointer_UTF8("\xee\x80\x8b");
    static inline String const ClearText = CharPointer_UTF8("\xee\x80\x8c");
    static inline String const Lock = CharPointer_UTF8("\xee\x80\x8d");
    static inline String const Play = CharPointer_UTF8("\xee\x80\x8d");
    static inline String const Power = CharPointer_UTF8("\xee\x80\x8e");
    static inline String const Audio = CharPointer_UTF8("\xee\x80\x8f");
    static inline String const Search = CharPointer_UTF8("\xee\x80\x90");
    static inline String const SearchFilled = CharPointer_UTF8("\xee\x80\x91");
    static inline String const Pencil = CharPointer_UTF8("\xee\x80\x92");
    static inline String const Grid = CharPointer_UTF8("\xee\x80\x93");
    static inline String const Keyboard = CharPointer_UTF8("\xee\x80\x94");
    static inline String const FolderFilled = CharPointer_UTF8("\xee\x80\x95");
    static inline String const OpenedFolder = CharPointer_UTF8("\xee\x80\x96");
    static inline String const File = CharPointer_UTF8("\xee\x80\x97");
    static inline String const New = CharPointer_UTF8("\xee\x80\x97");
    static inline String const AutoScroll = CharPointer_UTF8("\xee\x80\x98");
    static inline String const Restore = CharPointer_UTF8("\xee\x80\x99");
    static inline String const Error = CharPointer_UTF8("\xee\x80\x9a");
    static inline String const Message = CharPointer_UTF8("\xee\x80\x9b");
    static inline String const Parameters = CharPointer_UTF8("\xee\x80\x9c");
    static inline String const Presentation = CharPointer_UTF8("\xee\x80\x9d");
    static inline String const Externals = CharPointer_UTF8("\xee\x80\x9e");
    static inline String const ExternalsFilled = CharPointer_UTF8("\xee\x80\x9f");
    static inline String const Refresh = CharPointer_UTF8("\xee\x80\xa0");
    static inline String const Up = CharPointer_UTF8("\xee\x80\xa1");
    static inline String const Down = CharPointer_UTF8("\xee\x80\xa2");
    static inline String const Edit = CharPointer_UTF8("\xee\x80\xa3");
    static inline String const ChrevronDown = CharPointer_UTF8("\xee\x80\xa4");
    static inline String const ChrevronDownFilled = CharPointer_UTF8("\xee\x80\xa5");
    static inline String const Documentation = CharPointer_UTF8("\xee\x80\xa6");
    static inline String const Console = CharPointer_UTF8("\xee\x80\xa7");
    static inline String const OpenLink = CharPointer_UTF8("\xee\x80\xa8");
    static inline String const Wrench = CharPointer_UTF8("\xee\x80\xa9");
    static inline String const Back = CharPointer_UTF8("\xee\x80\xaa");
    static inline String const Forward = CharPointer_UTF8("\xee\x80\xab");
    static inline String const Menu = CharPointer_UTF8("\xee\x80\xac");
    static inline String const Info = CharPointer_UTF8("\xee\x80\xad");
    static inline String const Warning = CharPointer_UTF8("\xee\x80\xae");
    static inline String const History = CharPointer_UTF8("\xee\x80\xaf");
    static inline String const DevTools = CharPointer_UTF8("\xee\x80\xb0");
    static inline String const Help = CharPointer_UTF8("\xee\x80\xb1");
    static inline String const Checkmark = CharPointer_UTF8("\xee\x80\xb2");
    static inline String const Palette = CharPointer_UTF8("\xee\x80\xb3");
    static inline String const FitAll = CharPointer_UTF8("\xee\x80\xb4");
    static inline String const HeartStroked = CharPointer_UTF8("\xee\x80\xb4");
    static inline String const Eye = CharPointer_UTF8("\xee\x80\xb5");
    static inline String const Magnet = CharPointer_UTF8("\xee\x80\xb6");
    static inline String const SnapEdges = CharPointer_UTF8("\xee\x80\xb7");
    static inline String const SnapCenters = CharPointer_UTF8("\xee\x80\xb8");
    static inline String const ExportState = CharPointer_UTF8("\xee\x80\xb9");
    static inline String const Trash = CharPointer_UTF8("\xee\x80\xba");
    static inline String const Eyedropper = CharPointer_UTF8("\xee\x80\xbb");
    static inline String const HeartFilled = CharPointer_UTF8("\xee\x80\xbc");
    static inline String const Reset = CharPointer_UTF8("\xee\x80\xbd");
    static inline String const More = CharPointer_UTF8("\xee\x80\xbe");
    static inline String const MIDI = CharPointer_UTF8("\xee\x80\xbf");
    static inline String const PluginMode = CharPointer_UTF8("\xee\x81\x80");
    static inline String const Reorder = CharPointer_UTF8("\xee\x81\x81");
    static inline String const Object = CharPointer_UTF8("\xee\x81\x82");
    static inline String const ObjectFilled = CharPointer_UTF8("\xee\x81\x83");
    static inline String const ObjectMulti = CharPointer_UTF8("\xee\x81\x84");
    static inline String const List = CharPointer_UTF8("\xee\x81\x85");
    static inline String const Graph = CharPointer_UTF8("\xee\x81\x86");
    static inline String const Download = CharPointer_UTF8("\xee\x81\x87");
    static inline String const Copy = CharPointer_UTF8("\xee\x81\x88");
    static inline String const Paste = CharPointer_UTF8("\xee\x81\x89");
    static inline String const Duplicate = CharPointer_UTF8("\xee\x81\x8a");
    static inline String const Cut = CharPointer_UTF8("\xee\x81\x8b");
    static inline String const Storage = CharPointer_UTF8("\xee\x81\x8c");
    static inline String const Money = CharPointer_UTF8("\xee\x81\x8d");
    static inline String const Time = CharPointer_UTF8("\xee\x81\x8e");
    static inline String const Store = CharPointer_UTF8("\xee\x81\x8f");
    static inline String const PanelRight = CharPointer_UTF8("\xee\x81\x90");
    static inline String const ItemGrid = CharPointer_UTF8("\xee\x81\x91");
    static inline String const AlignLeft = CharPointer_UTF8("\xee\x81\x92");
    static inline String const AlignRight = CharPointer_UTF8("\xee\x81\x93");
    static inline String const AlignHCentre = CharPointer_UTF8("\xee\x81\x94");
    static inline String const AlignHDistribute = CharPointer_UTF8("\xee\x81\x95");
    static inline String const AlignTop = CharPointer_UTF8("\xee\x81\x96");
    static inline String const AlignBottom = CharPointer_UTF8("\xee\x81\x97");
    static inline String const AlignVCentre = CharPointer_UTF8("\xee\x81\x98");
    static inline String const AlignVDistribute = CharPointer_UTF8("\xee\x81\x99");
    static inline String const Home = CharPointer_UTF8("\xee\x81\x9a");
    static inline String const ShowIndex = CharPointer_UTF8("\xee\x81\x9b");
    static inline String const ShowXY = CharPointer_UTF8("\xee\x81\x9c");
    static inline String const Record = CharPointer_UTF8("\xee\x81\x9d");
    static inline String const AudioSettings = CharPointer_UTF8("\xee\x81\x9e");

    // OBJECT ICONS

    // generic
    static inline String const GlyphGenericSignal = CharPointer_UTF8("\xee\x81\x9f");
    static inline String const GlyphGeneric = CharPointer_UTF8("\xee\x81\xa0");

    // default
    static inline String const GlyphEmptyObject = CharPointer_UTF8("\xee\x81\xa1");
    static inline String const GlyphMessage = CharPointer_UTF8("\xee\x81\xa2");
    static inline String const GlyphFloatBox = CharPointer_UTF8("\xee\x81\xa3");
    static inline String const GlyphSymbolBox = CharPointer_UTF8("\xee\x81\xa4");
    static inline String const GlyphListBox = CharPointer_UTF8("\xee\x81\xa5");
    static inline String const GlyphComment = CharPointer_UTF8("\xee\x81\xa6");

    // ui
    static inline String const GlyphBang = CharPointer_UTF8("\xee\x81\xa7");
    static inline String const GlyphToggle = CharPointer_UTF8("\xee\x81\xa8");
    static inline String const GlyphButton = CharPointer_UTF8("\xee\x81\xa9");
    static inline String const GlyphKnob = CharPointer_UTF8("\xee\x81\xaa");
    static inline String const GlyphNumber = CharPointer_UTF8("\xee\x81\xab");
    static inline String const GlyphHSlider = CharPointer_UTF8("\xee\x81\xac");
    static inline String const GlyphVSlider = CharPointer_UTF8("\xee\x81\xad");
    static inline String const GlyphHRadio = CharPointer_UTF8("\xee\x81\xae");
    static inline String const GlyphVRadio = CharPointer_UTF8("\xee\x81\xaf");
    static inline String const GlyphCanvas = CharPointer_UTF8("\xee\x81\xb0");
    static inline String const GlyphKeyboard = CharPointer_UTF8("\xee\x81\xb1");
    static inline String const GlyphVUMeter = CharPointer_UTF8("\xee\x81\xb2");
    static inline String const GlyphArray = CharPointer_UTF8("\xee\x81\xb3");
    static inline String const GlyphGOP = CharPointer_UTF8("\xee\x81\xb4");
    static inline String const GlyphOscilloscope = CharPointer_UTF8("\xee\x81\xb5");
    static inline String const GlyphFunction = CharPointer_UTF8("\xee\x81\xb6");
    static inline String const GlyphMessbox = CharPointer_UTF8("\xee\x81\xb7");
    static inline String const GlyphBicoeff = CharPointer_UTF8("\xee\x81\xb8");

    // general
    static inline String const GlyphMetro = CharPointer_UTF8("\xee\x81\xb9");
    static inline String const GlyphCounter = CharPointer_UTF8("\xee\x81\xba");
    static inline String const GlyphSelect = CharPointer_UTF8("\xee\x81\xbb");
    static inline String const GlyphRoute = CharPointer_UTF8("\xee\x81\xbc");
    static inline String const GlyphExpr = CharPointer_UTF8("\xee\x81\xbd");
    static inline String const GlyphLoadbang = CharPointer_UTF8("\xee\x81\xbe");
    static inline String const GlyphPack = CharPointer_UTF8("\xee\x81\xbf");
    static inline String const GlyphUnpack = CharPointer_UTF8("\xee\x82\x80");
    static inline String const GlyphPrint = CharPointer_UTF8("\xee\x82\x81");
    static inline String const GlyphNetsend = CharPointer_UTF8("\xee\x82\x82");
    static inline String const GlyphNetreceive = CharPointer_UTF8("\xee\x82\x83");
    static inline String const GlyphOSCsend = CharPointer_UTF8("\xee\x82\x84");
    static inline String const GlyphOSCreceive = CharPointer_UTF8("\xee\x82\x85");
    static inline String const GlyphTimer = CharPointer_UTF8("\xee\x82\x86");
    static inline String const GlyphDelay = CharPointer_UTF8("\xee\x82\x87");
    static inline String const GlyphTrigger = CharPointer_UTF8("\xee\x82\x88");
    static inline String const GlyphMoses = CharPointer_UTF8("\xee\x82\x89");
    static inline String const GlyphSpigot = CharPointer_UTF8("\xee\x82\x8a");
    static inline String const GlyphBondo = CharPointer_UTF8("\xee\x82\x8b");
    static inline String const GlyphSfz = CharPointer_UTF8("\xee\x82\x8c");
    static inline String const GlyphMidiIn = CharPointer_UTF8("\xee\x82\x8d");
    static inline String const GlyphMidiOut = CharPointer_UTF8("\xee\x82\x8e");
    static inline String const GlyphNoteIn = CharPointer_UTF8("\xee\x82\x8f");
    static inline String const GlyphNoteOut = CharPointer_UTF8("\xee\x82\x90");
    static inline String const GlyphCtlIn = CharPointer_UTF8("\xee\x82\x91");
    static inline String const GlyphCtlOut = CharPointer_UTF8("\xee\x82\x92");
    static inline String const GlyphPgmIn = CharPointer_UTF8("\xee\x82\x93");
    static inline String const GlyphPgmOut = CharPointer_UTF8("\xee\x82\x94");
    static inline String const GlyphSysexIn = CharPointer_UTF8("\xee\x82\x95");
    static inline String const GlyphMtof = CharPointer_UTF8("\xee\x82\x96");
    static inline String const GlyphFtom = CharPointer_UTF8("\xee\x82\x97");
    static inline String const GlyphAutotune = CharPointer_UTF8("\xee\x82\x98");

    // Multi~
    static inline String const GlyphMultiSnake = CharPointer_UTF8("\xee\x82\x99");
    static inline String const GlyphMultiGet = CharPointer_UTF8("\xee\x82\x9a");
    static inline String const GlyphMultiPick = CharPointer_UTF8("\xee\x82\x9b");
    static inline String const GlyphMultiMerge = CharPointer_UTF8("\xee\x82\x9c");
    static inline String const GlyphMultiUnmerge = CharPointer_UTF8("\xee\x82\x9d");

    // IO~
    static inline String const GlyphAdc = CharPointer_UTF8("\xee\x82\x9e");
    static inline String const GlyphDac = CharPointer_UTF8("\xee\x82\x9f");
    static inline String const GlyphOut = CharPointer_UTF8("\xee\x82\xa0");
    static inline String const GlyphBlocksize = CharPointer_UTF8("\xee\x82\xa1");
    static inline String const GlyphSamplerate = CharPointer_UTF8("\xee\x82\xa2");
    static inline String const GlyphSetDsp = CharPointer_UTF8("\xee\x82\xa3");
    static inline String const GlyphSend = CharPointer_UTF8("\xee\x82\xa4");
    static inline String const GlyphReceive = CharPointer_UTF8("\xee\x82\xa5");
    static inline String const GlyphSignalSend = CharPointer_UTF8("\xee\x82\xa6");
    static inline String const GlyphSignalReceive = CharPointer_UTF8("\xee\x82\xa7");

    // OSC~
    static inline String const GlyphOsc = CharPointer_UTF8("\xee\x82\xa8");
    static inline String const GlyphPhasor = CharPointer_UTF8("\xee\x82\xa9");
    static inline String const GlyphSaw = CharPointer_UTF8("\xee\x82\xaa");
    static inline String const GlyphLFORamp = CharPointer_UTF8("\xee\x82\xaa");
    static inline String const GlyphSquare = CharPointer_UTF8("\xee\x82\xab");
    static inline String const GlyphTriangle = CharPointer_UTF8("\xee\x82\xac");
    static inline String const GlyphImp = CharPointer_UTF8("\xee\x82\xad");
    static inline String const GlyphWavetable = CharPointer_UTF8("\xee\x82\xae");
    static inline String const GlyphPlaits = CharPointer_UTF8("\xee\x82\xaf");
    static inline String const GlyphOscBL = CharPointer_UTF8("\xee\x82\xb0");
    static inline String const GlyphSawBL = CharPointer_UTF8("\xee\x82\xb1");
    static inline String const GlyphSquareBL = CharPointer_UTF8("\xee\x82\xb2");
    static inline String const GlyphTriBL = CharPointer_UTF8("\xee\x82\xb3");
    static inline String const GlyphImpBL = CharPointer_UTF8("\xee\x82\xb4");
    static inline String const GlyphWavetableBL = CharPointer_UTF8("\xee\x82\xb5");
    static inline String const GlyphLFOSaw = CharPointer_UTF8("\xee\x82\xb6");
    static inline String const GlyphLFOSquare = CharPointer_UTF8("\xee\x82\xb7");
    static inline String const GlyphPulse = CharPointer_UTF8("\xee\x82\xb8");
    static inline String const GlyphPinknoise = CharPointer_UTF8("\xee\x82\xb9");

    // effects~
    static inline String const GlyphCrusher = CharPointer_UTF8("\xee\x82\xba");
    static inline String const GlyphDelayEffect = CharPointer_UTF8("\xee\x82\xbb");
    static inline String const GlyphFreqShift = CharPointer_UTF8("\xee\x82\xbb");
    static inline String const GlyphDrive = CharPointer_UTF8("\xee\x82\xbc");
    static inline String const GlyphFlanger = CharPointer_UTF8("\xee\x82\xbd");
    static inline String const GlyphReverb = CharPointer_UTF8("\xee\x82\xbe");
    static inline String const GlyphFreeze = CharPointer_UTF8("\xee\x82\xbf");
    static inline String const GlyphRingmod = CharPointer_UTF8("\xee\x83\x80");
    static inline String const GlyphSVFilter = CharPointer_UTF8("\xee\x83\x81");
    static inline String const GlyphClip = CharPointer_UTF8("\xee\x83\x82");
    static inline String const GlyphFold = CharPointer_UTF8("\xee\x83\x83");
    static inline String const GlyphWrap = CharPointer_UTF8("\xee\x83\x84");
    static inline String const GlyphCombRev = CharPointer_UTF8("\xee\x83\x85");
    static inline String const GlyphComp = CharPointer_UTF8("\xee\x83\x86");
    static inline String const GlyphBallance = CharPointer_UTF8("\xee\x83\x87");
    static inline String const GlyphPan = CharPointer_UTF8("\xee\x83\x88");

    // filters~
    static inline String const GlyphLowpass = CharPointer_UTF8("\xee\x83\x89");
    static inline String const GlyphHighpass = CharPointer_UTF8("\xee\x83\x8a");
    static inline String const GlyphBandpass = CharPointer_UTF8("\xee\x83\x8b");
    static inline String const GlyphRezLowpass = CharPointer_UTF8("\xee\x83\x8c");
    static inline String const GlyphRezHighpass = CharPointer_UTF8("\xee\x83\x8d");
    static inline String const GlyphAllPass = CharPointer_UTF8("\xee\x83\x8e");

    // Patch
    static inline String const GlyphSubpatch = CharPointer_UTF8("\xee\x83\x8f");
    static inline String const GlyphInlet = CharPointer_UTF8("\xee\x83\x90");
    static inline String const GlyphOutlet = CharPointer_UTF8("\xee\x83\x91");
    static inline String const GlyphSignalInlet = CharPointer_UTF8("\xee\x83\x92");
    static inline String const GlyphSignalOutlet = CharPointer_UTF8("\xee\x83\x93");
    static inline String const GlyphClone = CharPointer_UTF8("\xee\x83\x94");
    static inline String const GlyphBlock = CharPointer_UTF8("\xee\x83\x95");
    static inline String const GlyphSwitch = CharPointer_UTF8("\xee\x83\x96");

    // User Interface
    static inline String const GlyphCircleSlider = CharPointer_UTF8("\xee\x83\x97");
    static inline String const GlyphIncdec = CharPointer_UTF8("\xee\x83\x98");
    static inline String const GlyphTabSelect = CharPointer_UTF8("\xee\x83\x99");
    static inline String const GlyphGuiCanvas = CharPointer_UTF8("\xee\x83\x9a");
    static inline String const GlyphSlider2D = CharPointer_UTF8("\xee\x83\x9b");
    static inline String const GlyphMousePad = CharPointer_UTF8("\xee\x83\x9c");
    static inline String const GlyphMultiSlider = CharPointer_UTF8("\xee\x83\x9d");
    static inline String const GlyphRangeSlider = CharPointer_UTF8("\xee\x83\x9e");
    static inline String const GlyphMatrixCtl = CharPointer_UTF8("\xee\x83\x9f");
    static inline String const GlyphDrumSeq = CharPointer_UTF8("\xee\x83\xa0");
    static inline String const GlyphPopmenu = CharPointer_UTF8("\xee\x83\xa1");
    static inline String const GlyphDisplay = CharPointer_UTF8("\xee\x83\xa2");
    static inline String const GlyphTextNote = CharPointer_UTF8("\xee\x83\xa3");
    static inline String const GlyphPic = CharPointer_UTF8("\xee\x83\xa4");
    static inline String const GlyphColors = CharPointer_UTF8("\xee\x83\xa5");
    static inline String const GlyphOpenFile = CharPointer_UTF8("\xee\x83\xa6");
    static inline String const GlyphBiplot = CharPointer_UTF8("\xee\x83\xa7");
    static inline String const GlyphZBiplot = CharPointer_UTF8("\xee\x83\xa8");
    static inline String const GlyphSignalNumbox = CharPointer_UTF8("\xee\x83\xa9");
    static inline String const GlyphGainFader = CharPointer_UTF8("\xee\x83\xaa");
    static inline String const GlyphGainFader2 = CharPointer_UTF8("\xee\x83\xab");
    static inline String const GlyphLevel = CharPointer_UTF8("\xee\x83\xac");
    static inline String const GlyphMeterBar = CharPointer_UTF8("\xee\x83\xad");
    static inline String const GlyphMeterBar2 = CharPointer_UTF8("\xee\x83\xae");
    static inline String const GlyphSpectrum = CharPointer_UTF8("\xee\x83\xaf");
    static inline String const GlyphScope3D = CharPointer_UTF8("\xee\x83\xb0");
    static inline String const GlyphPlaylist = CharPointer_UTF8("\xee\x83\xb1");

    // General
    static inline String const GlyphBangObject = CharPointer_UTF8("\xee\x83\xb2");
    static inline String const GlyphFloatObject = CharPointer_UTF8("\xee\x83\xb3");
    static inline String const GlyphIntObject = CharPointer_UTF8("\xee\x83\xb4");
    static inline String const GlyphSymbolObject = CharPointer_UTF8("\xee\x83\xb5");
    static inline String const GlyphValue = CharPointer_UTF8("\xee\x83\xb6");
    static inline String const GlyphChange = CharPointer_UTF8("\xee\x83\xb7");
    static inline String const GlyphSwap = CharPointer_UTF8("\xee\x83\xb8");
    static inline String const GlyphUntil = CharPointer_UTF8("\xee\x83\xb9");
    static inline String const GlyphChance = CharPointer_UTF8("\xee\x83\xba");
    static inline String const GlyphKeyInput = CharPointer_UTF8("\xee\x83\xbb");

    // Lists & Text
    static inline String const GlyphListAppend = CharPointer_UTF8("\xee\x83\xbc");
    static inline String const GlyphListPrepend = CharPointer_UTF8("\xee\x83\xbd");
    static inline String const GlyphListStore = CharPointer_UTF8("\xee\x83\xbe");
    static inline String const GlyphListSplit = CharPointer_UTF8("\xee\x83\xbf");
    static inline String const GlyphListLength = CharPointer_UTF8("\xee\x84\x80");
    static inline String const GlyphTextDefine = CharPointer_UTF8("\xee\x84\x81");
    static inline String const GlyphTextGet = CharPointer_UTF8("\xee\x84\x82");
    static inline String const GlyphTextSet = CharPointer_UTF8("\xee\x84\x83");
    static inline String const GlyphTextSeq = CharPointer_UTF8("\xee\x84\x84");
    static inline String const GlyphQlist = CharPointer_UTF8("\xee\x84\x85");
    static inline String const GlyphTextfile = CharPointer_UTF8("\xee\x84\x86");
    static inline String const GlyphFormat = CharPointer_UTF8("\xee\x84\x87");
    static inline String const GlyphMakeFilename = CharPointer_UTF8("\xee\x84\x88");

    // Time & Sequencing
    static inline String const GlyphPipe = CharPointer_UTF8("\xee\x84\x89");
    static inline String const GlyphScore = CharPointer_UTF8("\xee\x84\x8a");
    static inline String const GlyphSequencer = CharPointer_UTF8("\xee\x84\x8b");
    static inline String const GlyphEuclid = CharPointer_UTF8("\xee\x84\x8c");

    // MIDI
    static inline String const GlyphBendIn = CharPointer_UTF8("\xee\x84\x8d");
    static inline String const GlyphBendOut = CharPointer_UTF8("\xee\x84\x8e");
    static inline String const GlyphTouchIn = CharPointer_UTF8("\xee\x84\x8f");
    static inline String const GlyphTouchOut = CharPointer_UTF8("\xee\x84\x90");
    static inline String const GlyphPolyTouchIn = CharPointer_UTF8("\xee\x84\x91");
    static inline String const GlyphPolyTouchOut = CharPointer_UTF8("\xee\x84\x92");
    static inline String const GlyphMidiRealtime = CharPointer_UTF8("\xee\x84\x93");
    static inline String const GlyphMakenote = CharPointer_UTF8("\xee\x84\x94");
    static inline String const GlyphStripnote = CharPointer_UTF8("\xee\x84\x95");
    static inline String const GlyphPolyVoices = CharPointer_UTF8("\xee\x84\x96");
    static inline String const GlyphMidiLearn = CharPointer_UTF8("\xee\x84\x97");
    static inline String const GlyphPanic = CharPointer_UTF8("\xee\x84\x98");

    // Input & Output
    static inline String const GlyphOutMc = CharPointer_UTF8("\xee\x84\x99");
    static inline String const GlyphSigConv = CharPointer_UTF8("\xee\x84\x9a");
    static inline String const GlyphSnapshot = CharPointer_UTF8("\xee\x84\x9b");
    static inline String const GlyphThrow = CharPointer_UTF8("\xee\x84\x9c");
    static inline String const GlyphCatch = CharPointer_UTF8("\xee\x84\x9d");
    static inline String const GlyphSignalPrint = CharPointer_UTF8("\xee\x84\x9e");
    static inline String const GlyphOscParse = CharPointer_UTF8("\xee\x84\x9f");
    static inline String const GlyphOscFormat = CharPointer_UTF8("\xee\x84\xa0");
    static inline String const GlyphPdlink = CharPointer_UTF8("\xee\x84\xa1");

    // Arrays & Files
    static inline String const GlyphTabread = CharPointer_UTF8("\xee\x84\xa2");
    static inline String const GlyphTabread4 = CharPointer_UTF8("\xee\x84\xa3");
    static inline String const GlyphTabwrite = CharPointer_UTF8("\xee\x84\xa4");
    static inline String const GlyphSoundfiler = CharPointer_UTF8("\xee\x84\xa5");
    static inline String const GlyphBuffer = CharPointer_UTF8("\xee\x84\xa6");
    static inline String const GlyphSfload = CharPointer_UTF8("\xee\x84\xa7");
    static inline String const GlyphTabosc = CharPointer_UTF8("\xee\x84\xa8");
    static inline String const GlyphTabplay = CharPointer_UTF8("\xee\x84\xa9");
    static inline String const GlyphSignalTabread = CharPointer_UTF8("\xee\x84\xaa");
    static inline String const GlyphSignalTabread4 = CharPointer_UTF8("\xee\x84\xab");
    static inline String const GlyphSignalTabwrite = CharPointer_UTF8("\xee\x84\xac");
    static inline String const GlyphReadsf = CharPointer_UTF8("\xee\x84\xad");
    static inline String const GlyphWritesf = CharPointer_UTF8("\xee\x84\xae");
    static inline String const GlyphSamplePlayer = CharPointer_UTF8("\xee\x84\xaf");

    // Oscillators
    static inline String const GlyphCosine = CharPointer_UTF8("\xee\x84\xb0");
    static inline String const GlyphSine = CharPointer_UTF8("\xee\x84\xb1");
    static inline String const GlyphPulseOsc = CharPointer_UTF8("\xee\x84\xb2");
    static inline String const GlyphVSaw = CharPointer_UTF8("\xee\x84\xb3");
    static inline String const GlyphBlip = CharPointer_UTF8("\xee\x84\xb4");
    static inline String const GlyphFm = CharPointer_UTF8("\xee\x84\xb5");
    static inline String const GlyphPm = CharPointer_UTF8("\xee\x84\xb6");
    static inline String const GlyphWavetable2D = CharPointer_UTF8("\xee\x84\xb7");
    static inline String const GlyphOscBank = CharPointer_UTF8("\xee\x84\xb8");
    static inline String const GlyphLfo = CharPointer_UTF8("\xee\x84\xb9");

    // Noise & Random
    static inline String const GlyphNoise = CharPointer_UTF8("\xee\x84\xba");
    static inline String const GlyphPinkNoise = CharPointer_UTF8("\xee\x84\xbb");
    static inline String const GlyphBrownNoise = CharPointer_UTF8("\xee\x84\xbc");
    static inline String const GlyphCrackle = CharPointer_UTF8("\xee\x84\xbd");
    static inline String const GlyphDust = CharPointer_UTF8("\xee\x84\xbe");
    static inline String const GlyphLfNoise = CharPointer_UTF8("\xee\x84\xbf");
    static inline String const GlyphStepNoise = CharPointer_UTF8("\xee\x85\x80");
    static inline String const GlyphRampNoise = CharPointer_UTF8("\xee\x85\x81");
    static inline String const GlyphRandom = CharPointer_UTF8("\xee\x85\x82");
    static inline String const GlyphRandFloat = CharPointer_UTF8("\xee\x85\x83");
    static inline String const GlyphRandInt = CharPointer_UTF8("\xee\x85\x84");
    static inline String const GlyphDrunkard = CharPointer_UTF8("\xee\x85\x85");
    static inline String const GlyphMarkov = CharPointer_UTF8("\xee\x85\x86");

    // Envelopes
    static inline String const GlyphLineSignal = CharPointer_UTF8("\xee\x85\x87");
    static inline String const GlyphVline = CharPointer_UTF8("\xee\x85\x88");
    static inline String const GlyphLineCtl = CharPointer_UTF8("\xee\x85\x89");
    static inline String const GlyphAdsr = CharPointer_UTF8("\xee\x85\x8a");
    static inline String const GlyphAsr = CharPointer_UTF8("\xee\x85\x8b");
    static inline String const GlyphDecayEnv = CharPointer_UTF8("\xee\x85\x8c");
    static inline String const GlyphEnvGen = CharPointer_UTF8("\xee\x85\x8d");
    static inline String const GlyphFuncGen = CharPointer_UTF8("\xee\x85\x8e");
    static inline String const GlyphEnvelopeShape = CharPointer_UTF8("\xee\x85\x8f");
    static inline String const GlyphSusLoop = CharPointer_UTF8("\xee\x85\x90");
    static inline String const GlyphRampEnv = CharPointer_UTF8("\xee\x85\x91");
    static inline String const GlyphGlide = CharPointer_UTF8("\xee\x85\x92");
    static inline String const GlyphLag = CharPointer_UTF8("\xee\x85\x93");
    static inline String const GlyphSlew = CharPointer_UTF8("\xee\x85\x94");
    static inline String const GlyphSmooth = CharPointer_UTF8("\xee\x85\x95");

    // Filters
    static inline String const GlyphLop = CharPointer_UTF8("\xee\x85\x96");
    static inline String const GlyphHip = CharPointer_UTF8("\xee\x85\x97");
    static inline String const GlyphBpFilter = CharPointer_UTF8("\xee\x85\x98");
    static inline String const GlyphVcf = CharPointer_UTF8("\xee\x85\x99");
    static inline String const GlyphBiquad = CharPointer_UTF8("\xee\x85\x9a");
    static inline String const GlyphSlop = CharPointer_UTF8("\xee\x85\x9b");
    static inline String const GlyphLowpassRes = CharPointer_UTF8("\xee\x85\x9c");
    static inline String const GlyphHighpassRes = CharPointer_UTF8("\xee\x85\x9d");
    static inline String const GlyphBandpassRes = CharPointer_UTF8("\xee\x85\x9e");
    static inline String const GlyphBandstopFilt = CharPointer_UTF8("\xee\x85\x9f");
    static inline String const GlyphLowshelfFilt = CharPointer_UTF8("\xee\x85\xa0");
    static inline String const GlyphHighshelfFilt = CharPointer_UTF8("\xee\x85\xa1");
    static inline String const GlyphParametricEq = CharPointer_UTF8("\xee\x85\xa2");
    static inline String const GlyphAllpassFilt = CharPointer_UTF8("\xee\x85\xa3");
    static inline String const GlyphCombFilt = CharPointer_UTF8("\xee\x85\xa4");
    static inline String const GlyphResonantFilt = CharPointer_UTF8("\xee\x85\xa5");
    static inline String const GlyphCrossover = CharPointer_UTF8("\xee\x85\xa6");
    static inline String const GlyphMoog = CharPointer_UTF8("\xee\x85\xa7");

    // Effects
    static inline String const GlyphChorus = CharPointer_UTF8("\xee\x85\xa8");
    static inline String const GlyphPhaser = CharPointer_UTF8("\xee\x85\xa9");
    static inline String const GlyphTremolo = CharPointer_UTF8("\xee\x85\xaa");
    static inline String const GlyphVibrato = CharPointer_UTF8("\xee\x85\xab");
    static inline String const GlyphVocoder = CharPointer_UTF8("\xee\x85\xac");
    static inline String const GlyphWaveshaper = CharPointer_UTF8("\xee\x85\xad");
    static inline String const GlyphDownsample = CharPointer_UTF8("\xee\x85\xae");
    static inline String const GlyphPitchShift = CharPointer_UTF8("\xee\x85\xaf");
    static inline String const GlyphCompress = CharPointer_UTF8("\xee\x85\xb0");
    static inline String const GlyphExpand = CharPointer_UTF8("\xee\x85\xb1");
    static inline String const GlyphNoiseGate = CharPointer_UTF8("\xee\x85\xb2");
    static inline String const GlyphNormalize = CharPointer_UTF8("\xee\x85\xb3");
    static inline String const GlyphPlateReverb = CharPointer_UTF8("\xee\x85\xb4");
    static inline String const GlyphEchoReverb = CharPointer_UTF8("\xee\x85\xb5");
    static inline String const GlyphDelwrite = CharPointer_UTF8("\xee\x85\xb6");
    static inline String const GlyphDelread = CharPointer_UTF8("\xee\x85\xb7");

    // Analysis
    static inline String const GlyphEnvFollow = CharPointer_UTF8("\xee\x85\xb8");
    static inline String const GlyphRms = CharPointer_UTF8("\xee\x85\xb9");
    static inline String const GlyphPeakDetect = CharPointer_UTF8("\xee\x85\xba");
    static inline String const GlyphZerocross = CharPointer_UTF8("\xee\x85\xbb");
    static inline String const GlyphSigmund = CharPointer_UTF8("\xee\x85\xbc");
    static inline String const GlyphBonk = CharPointer_UTF8("\xee\x85\xbd");

    // Multichannel
    static inline String const GlyphNumChans = CharPointer_UTF8("\xee\x85\xbe");
    static inline String const GlyphMixChans = CharPointer_UTF8("\xee\x85\xbf");
    static inline String const GlyphSumChans = CharPointer_UTF8("\xee\x86\x80");
    static inline String const GlyphSliceChans = CharPointer_UTF8("\xee\x86\x81");
    static inline String const GlyphRepeatChans = CharPointer_UTF8("\xee\x86\x82");
    static inline String const GlyphGroupChans = CharPointer_UTF8("\xee\x86\x83");
    static inline String const GlyphSelectChans = CharPointer_UTF8("\xee\x86\x84");
    static inline String const GlyphLaceChans = CharPointer_UTF8("\xee\x86\x85");
    static inline String const GlyphDelaceChans = CharPointer_UTF8("\xee\x86\x86");

    // plugdata icon
    static inline String const PlugdataIconStandard = CharPointer_UTF8("\xee\x86\x87");
};
