/*
 // Copyright (c) 2022 Timothy Schoen and Wasted Audio
 // For information on usage and redistribution, and for a DISCLAIMER OF ALL
 // WARRANTIES, see the file, "LICENSE.txt," in this distribution.
 */

#pragma once

class HeavyCompatibleObjects {
    static inline StackArray<SmallString, 173> const heavyObjects = {
        "!=",
        "%",
        "&",
        "&&",
        "|",
        "||",
        "*",
        "+",
        "-",
        "/",
        "<",
        "<<",
        "<=",
        "==",
        ">",
        ">=",
        ">>",
        "abs",
        "atan",
        "atan2",
        "b",
        "bang",
        "bendin",
        "bendout",
        "block~", // ignored
        "bng",
        "canvas",
        "change",
        "clip",
        "cnv",
        "cos",
        "ctlin",
        "ctlout",
        "dbtopow",
        "dbtorms",
        "declare",
        "del",
        "delay",
        "div",
        "exp",
        "expr",
        "f",
        "float",
        "ftom",
        "graph",
        "gatom",
        "hradio",
        "hsl",
        "i",
        "inlet",
        "int",
        "line",
        "list",
        "loadbang",
        "log",
        "makenote",
        "max",
        "metro",
        "min",
        "midiin",
        "midiout",
        "midirealtimein",
        "mod",
        "moses",
        "mtof",
        "nbx",
        "notein",
        "noteout",
        "outlet",
        "pack",
        "pgmin",
        "pgmout",
        "pipe",
        "poly",
        "polytouchin",
        "polytouchout",
        "pow",
        "powtodb",
        "print",
        "r",
        "random",
        "receive",
        "rmstodb",
        "route",
        "s",
        "sel",
        "select",
        "send",
        "sin",
        "spigot",
        "sqrt",
        "stripnote",
        "swap",
        "symbol",
        "t",
        "table",
        "tabread",
        "tabwrite",
        "tan",
        "tgl",
        "timer",
        "touchin",
        "touchout",
        "trigger",
        "unpack",
        "until",
        "vradio",
        "vsl",
        "wrap",
        "*~",
        "+~",
        "-~",
        "/~",
        "abs~",
        "adc~",
        "bang~",
        "biquad~",
        "bp~",
        "catch~",
        "clip~",
        "cos~",
        "cpole~",
        "czero_rev~",
        "czero~",
        "dac~",
        "dbtopow~",
        "dbtorms~",
        "delread~",
        "delwrite~",
        "delread4~",
        "env~",
        "exp~",
        "expr~",
        "ftom~",
        "hip~",
        "inlet~",
        "line~",
        "lop~",
        "max~",
        "min~",
        "mtof~",
        "noise~",
        "osc~",
        "outlet~",
        "phasor~",
        "powtodb~",
        "pow~",
        "q8_rsqrt~",
        "q8_sqrt~",
        "receive~",
        "rmstodb~",
        "rpole~",
        "rsqrt~",
        "rzero_rev~",
        "rzero~",
        "r~",
        "samphold~",
        "samplerate~",
        "send~",
        "sig~",
        "snapshot~",
        "sqrt~",
        "s~",
        "tabosc4~",
        "tabplay~",
        "tabread4~",
        "tabread~",
        "tabwrite~",
        "threshold~",
        "throw~",
        "vcf~",
        "vd~",
        "wrap~"
    };

    // Heavylib abstractions:
    // These won't be used for the compatibility testing (it will recognise any abstractions as a canvas)
    // These are only for the suggestions
    static inline StackArray<SmallString, 31> const heavyAbstractions = {
        "hv.comb~",
        "hv.compressor~",
        "hv.compressor2~",
        "hv.dispatch",
        "hv.drunk",
        "hv.envfollow~",
        "hv.eq~",
        "hv.exp~",
        "hv.filter.gain~",
        "hv.filter.sig~",
        "hv.filter~",
        "hv.flanger~",
        "hv.flanger2~",
        "hv.freqshift~",
        "hv.gt~",
        "hv.gte~",
        "hv.hip~",
        "hv.lop~",
        "hv.log~",
        "hv.lt~",
        "hv.lfo",
        "hv.lte~",
        "hv.multiplex~",
        "hv.neq~",
        "hv.osc~",
        "hv.pinknoise~",
        "hv.pow~",
        "hv.reverb~",
        "hv.tanh~",
        "hv.vline~"
    };

    static inline StackArray<SmallString, 32> const cycloneObjects = {
        "acosh~",
        "acos~",
        "asinh~",
        "asin~",
        "atan2~",
        "atanh~",
        "atan~",
        "bitand~",
        "bitor~",
        "bitnot~",
        "bitsafe~",
        "bitxor~",
        "cartopol~",
        "cosh~",
        "cosx~",
        "equals~",
        "==~",
        "greaterthaneq~",
        ">=~",
        "greaterthan~",
        ">~",
        "lessthaneq~",
        "<=~",
        "lessthan~",
        "<~",
        "notequals~",
        "!=~",
        "poltocar~",
        "sinh~",
        "sinx~",
        "tanh~",
        "tanx~",
    };

    static inline StackArray<SmallString, 2> const otherObjects = {
        "pdnam~",
        "knob" // from ELSE library
    };


    static inline StackArray<SmallString, 8> const elseAbstractions = {
        "above",
        "add",
        "avg",
        "car2pol",
        "nop~",
        "sysrt.in",
        "sysrt.out",
        "trig2bang",
        // "float2sig.unit",
        // "out.mc.hip~",
        // "sendmidi",
    };

    static inline StackArray<SmallString, 5> const pdAbstractions = {
        "complex-mod~",
        "hilbert~",
        "rev1~",
        "rev2~",
        "rev3~",
    };

    static inline StackArray<SmallString, 6> const extra = {
        "comment",
        "floatbox",
        "symbolbox",
        "msg",
        "message",
        "invalid",
    };

    static HeapArray<SmallString> initialiseCompatibleObjects()
    {
        HeapArray<SmallString> allObjects;
        allObjects.add_array(heavyObjects);
        allObjects.add_array(heavyAbstractions);
        allObjects.add_array(cycloneObjects);
        allObjects.add_array(otherObjects);
        allObjects.add_array(elseAbstractions);
        allObjects.add_array(pdAbstractions);
        allObjects.add_array(extra);

        return allObjects;
    }

    static inline HeapArray<SmallString> allCompatibleObjects = initialiseCompatibleObjects();

public:
    static bool isCompatible(SmallString const& type)
    {
        return allCompatibleObjects.contains(type.upToFirstOccurrenceOf(" "));
    }
};
