/* WARNING! All changes made to this file will be lost! */

#ifndef W_SRC_CONFIG_H_WAF
#define W_SRC_CONFIG_H_WAF

#define HAVE_STDLIB_H 1
#define HAVE_STDIO_H 1
#define HAVE_MATH_H 1
#define HAVE_STRING_H 1
#define HAVE_ERRNO_H 1
#define HAVE_LIMITS_H 1
#define HAVE_STDARG_H 1
#define HAVE_GETOPT_H 1
#define HAVE_UNISTD_H 1
#define NDEBUG 1
#undef HAVE_SOURCE_APPLE_AUDIO
#undef HAVE_SINK_APPLE_AUDIO
#undef HAVE_ACCELERATE
#define HAVE_C99_VARARGS_MACROS 1
#undef HAVE_SNDFILE
#undef HAVE_SAMPLERATE
#undef HAVE_RUBBERBAND
#undef HAVE_AVCODEC
#undef HAVE_AVFORMAT
#undef HAVE_AVUTIL
#undef HAVE_SWRESAMPLE
#undef HAVE_LIBAV
#undef HAVE_VORBISENC
#undef HAVE_FLAC
#undef HAVE_WAVREAD
#undef HAVE_WAVWRITE
#undef HAVE_MEMCPY_HACKS

#endif /* W_SRC_CONFIG_H_WAF */
