
#define SYSFLAG_PY3K_WARNING 0
#define SYSFLAG_DIVISION_WARNING 0
#define SYSFLAG_UNICODE 1
#define SYSFLAG_OPTIMIZE 1
#define SYSFLAG_NO_SITE 1
#define SYSFLAG_VERBOSE 0
#define SYSFLAG_BYTES_WARNING 0
#define SYSFLAG_UTF8 1
#define SYSFLAG_UNBUFFERED 0