/* fluid_config.h will be generated by cmake from this file: src/fluid_config.cmake */

/* Activate debugging message */
#cmakedefine01 DEBUG

/* Version number of the package */
#define VERSION "@fluidlite_VERSION@"

/* Defined to 1 if the processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
#cmakedefine WORDS_BIGENDIAN

/* SF3 files support, using OGG/Vorbis */
#define SF3_DISABLED 0
#define SF3_XIPH_VORBIS 1
#define SF3_STB_VORBIS 2
#define SF3_SUPPORT @SF3_SUPPORT@

/* if defined, the synth uses float (32 bit) samples, otherwise it uses double (64 bit) samples */
#cmakedefine WITH_FLOAT

/* Standard C99 headers detection */ 
#cmakedefine01 HAVE_STRING_H
#cmakedefine01 HAVE_STDLIB_H
#cmakedefine01 HAVE_STDIO_H
#cmakedefine01 HAVE_STDARG_H
#cmakedefine01 HAVE_MATH_H
#cmakedefine01 HAVE_LIMITS_H
#cmakedefine01 HAVE_FCNTL_H

//#pragma warning(disable : 4244)
//#pragma warning(disable : 4101)
//#pragma warning(disable : 4305)
//#pragma warning(disable : 4996)
